services:
  newanimeeposidenotifier:
    build:
      context: .
    volumes:
      - ./mnt:/mnt:ro
    user: "33:33"
    read_only: true
    networks:
      - main

networks:
  main:
    name: main
    external: true
